# Generated by Django 4.0.4 on 2022-06-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('size', models.CharField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(default=None, upload_to='uploads')),
            ],
        ),
    ]
