# Generated by Django 4.0.4 on 2022-06-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='size',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
